In [1583]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [1584]:
df = pd.read_csv("ecommerce_customer_behavior_dataset.csv")

In [1585]:
df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_001337,CUST_01337,2023-01-01,27,Female,Bursa,Toys,54.28,1,0.00,54.28,Debit Card,Mobile,4,14,True,8,5
1,ORD_004885,CUST_04885,2023-01-01,42,Male,Konya,Toys,244.90,1,0.00,244.90,Credit Card,Mobile,11,3,True,3,3
2,ORD_004507,CUST_04507,2023-01-01,43,Female,Ankara,Food,48.15,5,0.00,240.75,Credit Card,Mobile,7,8,True,5,2
3,ORD_000645,CUST_00645,2023-01-01,32,Male,Istanbul,Electronics,804.06,1,229.28,574.78,Credit Card,Mobile,8,10,False,1,4
4,ORD_000690,CUST_00690,2023-01-01,40,Female,Istanbul,Sports,755.61,5,0.00,3778.05,Cash on Delivery,Desktop,21,10,True,7,4

In [1586]:
id_list = df['Order_ID'].tolist()

for i in range(len(id_list)):
    id_list[i] = id_list[i][4:]
    for j in range(len(id_list[i])):
        if id_list[i][j] == 0:
            id_list[i][j] = id_list[i][j].replace("0","")
    id_list[i] = int(id_list[i])

In [1587]:
id_list

[1337,
 4885,
 4507,
 645,
 690,
 223,
 2506,
 4540,
 1808,
 3413,
 4457,
 4797,
 1211,
 514,
 3462,
 1418,
 198,
 374,
 3204,
 4204,
 751,
 2466,
 3920,
 38,
 3721,
 2069,
 2080,
 285,
 846,
 3744,
 3991,
 3301,
 4873,
 2003,
 3730,
 1602,
 477,
 2957,
 1565,
 527,
 4551,
 4850,
 450,
 3803,
 4585,
 3246,
 4291,
 4550,
 4883,
 182,
 4113,
 4744,
 1054,
 3313,
 3948,
 991,
 4801,
 1144,
 4740,
 4656,
 3748,
 3622,
 1373,
 4676,
 1127,
 3274,
 1822,
 359,
 1477,
 1690,
 3755,
 3743,
 4501,
 2535,
 3836,
 3039,
 2497,
 3749,
 4673,
 1072,
 3669,
 1829,
 3491,
 3083,
 227,
 2321,
 2468,
 2102,
 912,
 1284,
 839,
 2117,
 2525,
 279,
 1784,
 928,
 1597,
 3464,
 4168,
 2937,
 3409,
 729,
 4875,
 1709,
 4136,
 568,
 601,
 3,
 24,
 955,
 4628,
 880,
 1820,
 2701,
 1989,
 3052,
 4043,
 2433,
 2759,
 3937,
 1276,
 885,
 866,
 1995,
 1364,
 1529,
 1036,
 4196,
 619,
 2849,
 2444,
 1860,
 2014,
 924,
 18,
 2863,
 4995,
 4312,
 3882,
 4764,
 2664,
 1755,
 3078,
 3427,
 4358,
 2681,
 1218,
 3794,
 3485,
 3832,
 4317,
 292,
 126,
 17,
 3713,
 2671,
 1641,
 3497,
 3235,
 1508,
 2572,
 1325,
 533,
 1464,
 4810,
 2587,
 4084,
 1727,
 2344,
 3230,
 626,
 2454,
 3245,
 2208,
 587,
 3006,
 1290,
 1270,
 546,
 2249,
 4977,
 4679,
 3606,
 922,
 1637,
 3004,
 425,
 2227,
 3817,
 4343,
 981,
 2100,
 3163,
 2578,
 541,
 2644,
 2846,
 4904,
 513,
 4102,
 2575,
 60,
 642,
 4164,
 4798,
 1450,
 3506,
 1851,
 2551,
 2364,
 2529,
 1530,
 3663,
 2968,
 2851,
 2064,
 730,
 1132,
 4803,
 3418,
 4495,
 3005,
 1726,
 78,
 3825,
 4836,
 3719,
 2595,
 3551,
 163,
 3503,
 4494,
 2484,
 2946,
 2947,
 1785,
 1608,
 3188,
 764,
 4989,
 2037,
 401,
 355,
 893,
 2913,
 1353,
 4831,
 1152,
 915,
 3600,
 1832,
 1954,
 4527,
 507,
 3194,
 2970,
 2267,
 2032,
 2406,
 3063,
 2435,
 1133,
 1343,
 324,
 4288,
 1165,
 4643,
 3868,
 123,
 4732,
 2805,
 3515,
 2201,
 2068,
 3395,
 4780,
 3801,
 1533,
 393,
 2209,
 235,
 3402,
 2653,
 408,
 3578,
 4724,
 400,
 3424,
 3711,
 4413,
 3220,
 4390,
 4899,
 289,
 4680,
 2880,
 3735,
 1939,
 1194,
 1247,
 371,
 397,
 3372,
 2238,
 3540,
 4924,
 1861,
 3319,
 329,
 1770,
 831,
 3100,
 3969,
 4213,
 824,
 173,
 1839,
 2568,
 2491,
 4470,
 3422,
 1716,
 4770,
 277,
 2736,
 1876,
 2272,
 1158,
 4717,
 2770,
 131,
 3494,
 4675,
 415,
 4162,
 2538,
 1926,
 2673,
 2518,
 2193,
 291,
 3727,
 462,
 77,
 4053,
 244,
 987,
 608,
 3425,
 919,
 2010,
 413,
 4582,
 1407,
 1510,
 657,
 1793,
 4838,
 295,
 103,
 4561,
 286,
 1246,
 2096,
 4654,
 1226,
 2977,
 449,
 4672,
 3608,
 2786,
 3417,
 3905,
 2782,
 1161,
 1572,
 2878,
 2723,
 4072,
 736,
 455,
 1871,
 2204,
 4943,
 1674,
 1209,
 4440,
 3873,
 963,
 2171,
 348,
 529,
 2654,
 1484,
 3826,
 3716,
 4921,
 3977,
 2145,
 4775,
 2213,
 3845,
 2104,
 2333,
 2690,
 807,
 3369,
 4543,
 4825,
 1548,
 3777,
 2621,
 83,
 3166,
 2820,
 3864,
 66,
 239,
 3591,
 2467,
 2630,
 4702,
 2135,
 2441,
 1204,
 2039,
 3444,
 2850,
 1493,
 2287,
 1268,
 3363,
 1872,
 410,
 815,
 427,
 910,
 3789,
 4700,
 4693,
 3806,
 4310,
 3906,
 2618,
 2419,
 886,
 4522,
 3898,
 4251,
 1057,
 4618,
 2031,
 712,
 1171,
 3953,
 1929,
 2300,
 2245,
 240,
 4141,
 2515,
 4092,
 4913,
 2769,
 4847,
 3292,
 4726,
 1025,
 4602,
 4364,
 14,
 3928,
 2728,
 1327,
 4564,
 2126,
 3222,
 3938,
 4968,
 3391,
 2015,
 4537,
 2217,
 1927,
 1517,
 2938,
 1277,
 1687,
 2428,
 3919,
 161,
 1778,
 1646,
 1305,
 4983,
 51,
 508,
 2315,
 4462,
 719,
 1376,
 1073,
 19,
 3941,
 2831,
 4903,
 4518,
 3595,
 4445,
 360,
 3795,
 1930,
 3815,
 4408,
 4539,
 2274,
 4915,
 314,
 1916,
 3295,
 3764,
 53,
 1731,
 2912,
 1932,
 4156,
 2990,
 315,
 1634,
 1197,
 1519,
 2446,
 1749,
 1893,
 328,
 4114,
 3869,
 354,
 1764,
 4496,
 3652,
 454,
 4603,
 2337,
 3200,
 1470,
 87,
 3195,
 1119,
 1524,
 1474,
 3495,
 2240,
 969,
 50,
 4789,
 4567,
 2629,
 4350,
 2161,
 3926,
 4215,
 2412,
 4568,
 552,
 10,
 3936,
 1142,
 1959,
 4138,
 4893,
 483,
 1312,
 2544,
 4951,
 2129,
 488,
 3250,
 755,
 3918,
 4112,
 3988,
 3763,
 2903,
 1588,
 996,
 207,
 1968,
 953,
 627,
 3182,
 335,
 4172,
 4093,
 1846,
 1867,
 1705,
 584,
 4949,
 2959,
 2492,
 2055,
 3081,
 3043,
 2478,
 1817,
 165,
 528,
 3484,
 228,
 3371,
 193,
 2,
 4649,
 3265,
 4332,
 4167,
 1379,
 2052,
 948,
 4334,
 4237,
 2115,
 1896,
 1156,
 4224,
 1837,
 1238,
 935,
 2148,
 185,
 1973,
 4034,
 2700,
 1672,
 1331,
 637,
 4142,
 4258,
 620,
 487,
 3385,
 4793,
 1724,
 4728,
 1730,
 2988,
 3321,
 3332,
 2708,
 4762,
 3626,
 3453,
 1173,
 4367,
 4255,
 1381,
 4555,
 2079,
 1102,
 4967,
 274,
 1098,
 4739,
 420,
 977,
 4957,
 4828,
 1363,
 768,
 2752,
 3151,
 1945,
 2720,
 2483,
 1774,
 2907,
 1257,
 2417,
 64,
 2600,
 664,
 1693,
 4606,
 2807,
 4502,
 1137,
 1465,
 2672,
 1877,
 1833,
 4756,
 1789,
 2826,
 1130,
 2783,
 248,
 932,
 4417,
 2792,
 3458,
 2989,
 2308,
 540,
 249,
 877,
 676,
 4486,
 1937,
 2767,
 4927,
 2085,
 2297,
 2898,
 1812,
 517,
 2801,
 4420,
 1653,
 460,
 1357,
 1645,
 1821,
 303,
 4559,
 4544,
 442,
 4659,
 2350,
 3927,
 4511,
 3397,
 770,
 3449,
 3584,
 4578,
 3339,
 4917,
 485,
 2961,
 3258,
 4253,
 2550,
 4409,
 4945,
 4293,
 1405,
 3432,
 2567,
 1734,
 889,
 2721,
 3989,
 4008,
 2453,
 4742,
 3723,
 3102,
 3203,
 4572,
 2331,
 158,
 2692,
 1632,
 3181,
 2403,
 816,
 2074,
 4267,
 3007,
 3017,
 4384,
 8,
 3963,
 3860,
 341,
 3297,
 145,
 2755,
 3704,
 4614,
 3516,
 4282,
 4604,
 1725,
 2460,
 4061,
 4432,
 1675,
 2011,
 2290,
 1245,
 2911,
 4145,
 4262,
 4900,
 2006,
 2889,
 3533,
 1479,
 2998,
 3839,
 143,
 4581,
 2503,
 2665,
 3575,
 1557,
 4422,
 2162,
 1811,
 3668,
 3968,
 1538,
 1398,
 2452,
 3161,
 1875,
 2425,
 3074,
 748,
 2159,
 728,
 538,
 1805,
 4982,
 1167,
 3766,
 531,
 1428,
 2472,
 3379,
 3014,
 3562,
 2285,
 1242,
 4807,
 3729,
 4134,
 4595,
 4872,
 2191,
 1166,
 817,
 3087,
 2237,
 1462,
 2353,
 3341,
 1384,
 216,
 930,
 1003,
 4067,
 1923,
 2167,
 2809,
 166,
 2683,
 821,
 2837,
 3908,
 3913,
 4698,
 3677,
 2332,
 4950,
 389,
 4706,
 560,
 3478,
 46,
 491,
 1483,
 1746,
 1963,
 2033,
 2034,
 2023,
 196,
 4504,
 2881,
 3206,
 1571,
 4969,
 1205,
 407,
 2742,
 1210,
 467,
 4786,
 1370,
 2929,
 788,
 3324,
 2921,
 2257,
 41,
 4181,
 581,
 4514,
 168,
 2663,
 2398,
 2421,
 1314,
 520,
 219,
 2812,
 951,
 2354,
 94,
 3847,
 110,
 3267,
 563,
 4745,
 3021,
 4588,
 2361,
 4175,
 874,
 4382,
 2811,
 372,
 1662,
 253,
 4952,
 1248,
 3380,
 4526,
 1526,
 364,
 943,
 4099,
 4754,
 4279,
 4309,
 2639,
 4784,
 3970,
 3703,
 710,
 4397,
 4322,
 3959,
 2144,
 3699,
 3962,
 2834,
 2119,
 3805,
 3066,
 106,
 2838,
 1546,
 4668,
 4243,
 4277,
 2165,
 2248,
 2725,
 1207,
 3112,
 4738,
 1816,
 2084,
 683,
 4994,
 1830,
 2747,
 1651,
 4179,
 2557,
 1293,
 1547,
 3545,
 3231,
 3283,
 2172,
 4016,
 3234,
 1005,
 566,
 759,
 3762,
 3833,
 623,
 1125,
 569,
 3454,
 4808,
 4832,
 205,
 1545,
 3430,
 2355,
 1299,
 4039,
 2625,
 ...]

In [1588]:
df['Customer_ID'] = id_list
df.drop('Order_ID', axis=1, inplace=True)

In [1589]:
df.head()

,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,1337,2023-01-01,27,Female,Bursa,Toys,54.28,1,0.00,54.28,Debit Card,Mobile,4,14,True,8,5
1,4885,2023-01-01,42,Male,Konya,Toys,244.90,1,0.00,244.90,Credit Card,Mobile,11,3,True,3,3
2,4507,2023-01-01,43,Female,Ankara,Food,48.15,5,0.00,240.75,Credit Card,Mobile,7,8,True,5,2
3,645,2023-01-01,32,Male,Istanbul,Electronics,804.06,1,229.28,574.78,Credit Card,Mobile,8,10,False,1,4
4,690,2023-01-01,40,Female,Istanbul,Sports,755.61,5,0.00,3778.05,Cash on Delivery,Desktop,21,10,True,7,4

In [1590]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek
df['Quarter'] = df['Date'].dt.quarter
df['IsWeekend'] = df['DayOfWeek'].isin([5, 6]).astype(int)
df = df.drop(columns='Date')

In [1591]:
df.head()

,Customer_ID,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend
0,1337,27,Female,Bursa,Toys,54.28,1,0.00,54.28,Debit Card,Mobile,4,14,True,8,5,2023,1,1,6,1,1
1,4885,42,Male,Konya,Toys,244.90,1,0.00,244.90,Credit Card,Mobile,11,3,True,3,3,2023,1,1,6,1,1
2,4507,43,Female,Ankara,Food,48.15,5,0.00,240.75,Credit Card,Mobile,7,8,True,5,2,2023,1,1,6,1,1
3,645,32,Male,Istanbul,Electronics,804.06,1,229.28,574.78,Credit Card,Mobile,8,10,False,1,4,2023,1,1,6,1,1
4,690,40,Female,Istanbul,Sports,755.61,5,0.00,3778.05,Cash on Delivery,Desktop,21,10,True,7,4,2023,1,1,6,1,1

In [1592]:
df.isnull().sum()

Customer_ID                 0
Age                         0
Gender                      0
City                        0
Product_Category            0
Unit_Price                  0
Quantity                    0
Discount_Amount             0
Total_Amount                0
Payment_Method              0
Device_Type                 0
Session_Duration_Minutes    0
Pages_Viewed                0
Is_Returning_Customer       0
Delivery_Time_Days          0
Customer_Rating             0
Year                        0
Month                       0
Day                         0
DayOfWeek                   0
Quarter                     0
IsWeekend                   0
dtype: int64

In [1593]:
df['Discount_Percentage'] = (df['Discount_Amount'] / (df['Unit_Price'] * df['Quantity'])) * 100

In [1594]:
df['Avg_Spending_City'] = df.groupby('City')['Total_Amount'].transform('mean')

In [1595]:
total_amount = df["Total_Amount"]
df.drop(columns=['Discount_Amount', 'Total_Amount'], inplace=True)

In [1596]:
df.head()

,Customer_ID,Age,Gender,City,Product_Category,Unit_Price,Quantity,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City
0,1337,27,Female,Bursa,Toys,54.28,1,Debit Card,Mobile,4,14,True,8,5,2023,1,1,6,1,1,0.000000,925.557077
1,4885,42,Male,Konya,Toys,244.90,1,Credit Card,Mobile,11,3,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022
2,4507,43,Female,Ankara,Food,48.15,5,Credit Card,Mobile,7,8,True,5,2,2023,1,1,6,1,1,0.000000,894.606558
3,645,32,Male,Istanbul,Electronics,804.06,1,Credit Card,Mobile,8,10,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262
4,690,40,Female,Istanbul,Sports,755.61,5,Cash on Delivery,Desktop,21,10,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262

In [1597]:
df['City'].unique()

array(['Bursa', 'Konya', 'Ankara', 'Istanbul', 'Izmir', 'Eskisehir',
       'Antalya', 'Kayseri', 'Gaziantep', 'Adana'], dtype=object)

In [1598]:
df.drop(columns='City', inplace=True)

In [1599]:
df.head()

,Customer_ID,Age,Gender,Product_Category,Unit_Price,Quantity,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City
0,1337,27,Female,Toys,54.28,1,Debit Card,Mobile,4,14,True,8,5,2023,1,1,6,1,1,0.000000,925.557077
1,4885,42,Male,Toys,244.90,1,Credit Card,Mobile,11,3,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022
2,4507,43,Female,Food,48.15,5,Credit Card,Mobile,7,8,True,5,2,2023,1,1,6,1,1,0.000000,894.606558
3,645,32,Male,Electronics,804.06,1,Credit Card,Mobile,8,10,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262
4,690,40,Female,Sports,755.61,5,Cash on Delivery,Desktop,21,10,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262

In [1600]:
#df['Gender'] = df['Gender'].map({'Male' : '1', 'Female' : '0'})

In [1601]:
#df.head()

In [1602]:
df['Product_Category'].unique()

array(['Toys', 'Food', 'Electronics', 'Sports', 'Beauty', 'Fashion',
       'Home & Garden', 'Books'], dtype=object)

In [1603]:
df = pd.get_dummies(df, columns=['Product_Category'], prefix='Product')

In [1604]:
df.head()

,Customer_ID,Age,Gender,Unit_Price,Quantity,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys
0,1337,27,Female,54.28,1,Debit Card,Mobile,4,14,True,8,5,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True
1,4885,42,Male,244.90,1,Credit Card,Mobile,11,3,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True
2,4507,43,Female,48.15,5,Credit Card,Mobile,7,8,True,5,2,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False
3,645,32,Male,804.06,1,Credit Card,Mobile,8,10,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False
4,690,40,Female,755.61,5,Cash on Delivery,Desktop,21,10,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False

In [1605]:
df['Payment_Method'].unique()

array(['Debit Card', 'Credit Card', 'Cash on Delivery', 'Digital Wallet',
       'Bank Transfer'], dtype=object)

In [1606]:
payment_method = df['Payment_Method']
df = pd.get_dummies(df, columns=['Payment_Method'], prefix='Payment')

In [1607]:
df.head()

,Customer_ID,Age,Gender,Unit_Price,Quantity,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet
0,1337,27,Female,54.28,1,Mobile,4,14,True,8,5,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False
1,4885,42,Male,244.90,1,Mobile,11,3,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False
2,4507,43,Female,48.15,5,Mobile,7,8,True,5,2,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False
3,645,32,Male,804.06,1,Mobile,8,10,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False
4,690,40,Female,755.61,5,Desktop,21,10,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False

In [1608]:
df['Device_Type'].unique()

array(['Mobile', 'Desktop', 'Tablet'], dtype=object)

In [1609]:
df = pd.get_dummies(df, columns=['Device_Type'], prefix='Device')

In [1610]:
df.head()

,Customer_ID,Age,Gender,Unit_Price,Quantity,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet
0,1337,27,Female,54.28,1,4,14,True,8,5,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False
1,4885,42,Male,244.90,1,11,3,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
2,4507,43,Female,48.15,5,7,8,True,5,2,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False
3,645,32,Male,804.06,1,8,10,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
4,690,40,Female,755.61,5,21,10,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False

In [1611]:
len(df['Customer_ID'].unique())

5000

In [1612]:
df.drop(columns='Customer_ID', inplace=True)

In [1613]:
df.head()

,Age,Gender,Unit_Price,Quantity,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet
0,27,Female,54.28,1,4,14,True,8,5,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False
1,42,Male,244.90,1,11,3,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False
2,43,Female,48.15,5,7,8,True,5,2,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False
3,32,Male,804.06,1,8,10,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
4,40,Female,755.61,5,21,10,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False

In [1614]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['Engagement_Score'] = scaler.fit_transform(
    (df['Session_Duration_Minutes'] * df['Pages_Viewed']).values.reshape(-1,1)
)

df['Pages_per_Minute'] = df['Pages_Viewed'] / df['Session_Duration_Minutes']

df['Browsing_to_Delivery_Ratio'] = df['Pages_per_Minute'] / df['Delivery_Time_Days']

df.drop(columns=['Session_Duration_Minutes', 'Pages_Viewed'], inplace=True)

In [1615]:
df.head()

,Age,Gender,Unit_Price,Quantity,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet,Engagement_Score,Pages_per_Minute,Browsing_to_Delivery_Ratio
0,27,Female,54.28,1,True,8,5,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,0.060433,3.500000,0.437500
1,42,Male,244.90,1,True,3,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,0.034208,0.272727,0.090909
2,43,Female,48.15,5,True,5,2,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,0.060433,1.142857,0.228571
3,32,Male,804.06,1,False,1,4,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,0.087799,1.250000,1.250000
4,40,Female,755.61,5,True,7,4,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,0.236032,0.476190,0.068027

In [1616]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df['Customer_Rating'] = scaler.fit_transform(df[['Customer_Rating']])

In [1617]:
df.head()

,Age,Gender,Unit_Price,Quantity,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet,Engagement_Score,Pages_per_Minute,Browsing_to_Delivery_Ratio
0,27,Female,54.28,1,True,8,1.00,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,0.060433,3.500000,0.437500
1,42,Male,244.90,1,True,3,0.50,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,0.034208,0.272727,0.090909
2,43,Female,48.15,5,True,5,0.25,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,0.060433,1.142857,0.228571
3,32,Male,804.06,1,False,1,0.75,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,0.087799,1.250000,1.250000
4,40,Female,755.61,5,True,7,0.75,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,0.236032,0.476190,0.068027

In [1618]:
avg_rating = df['Customer_Rating'].mean()
df['Rating_Deviation'] = df['Customer_Rating'] - avg_rating

df.drop(columns=['Customer_Rating'], inplace=True)

In [1619]:
df.head()

,Age,Gender,Unit_Price,Quantity,Is_Returning_Customer,Delivery_Time_Days,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet,Engagement_Score,Pages_per_Minute,Browsing_to_Delivery_Ratio,Rating_Deviation
0,27,Female,54.28,1,True,8,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,0.060433,3.500000,0.437500,0.2743
1,42,Male,244.90,1,True,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,0.034208,0.272727,0.090909,-0.2257
2,43,Female,48.15,5,True,5,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,0.060433,1.142857,0.228571,-0.4757
3,32,Male,804.06,1,False,1,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,0.087799,1.250000,1.250000,0.0243
4,40,Female,755.61,5,True,7,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,0.236032,0.476190,0.068027,0.0243

In [1620]:
bins = [0, 18, 25, 35, 50, 65, 100]
labels = ['Teen', 'Young_Adult', 'Adult', 'Middle_Aged', 'Senior', 'Elder']

df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)
age_group = df['Age_Group']

df['Demo_Segment'] = df['Gender'].astype(str) + '_' + df['Age_Group'].astype(str)
demo_seg = df['Demo_Segment']

In [1621]:
df = pd.get_dummies(df, columns=['Age_Group'], prefix='Age')
df = pd.get_dummies(df, columns=['Demo_Segment'], prefix='Seg')

In [1622]:
df.head()

,Age,Gender,Unit_Price,Quantity,Is_Returning_Customer,Delivery_Time_Days,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet,Engagement_Score,Pages_per_Minute,Browsing_to_Delivery_Ratio,Rating_Deviation,Age_Teen,Age_Young_Adult,Age_Adult,Age_Middle_Aged,Age_Senior,Age_Elder,Seg_Female_Adult,Seg_Female_Elder,Seg_Female_Middle_Aged,Seg_Female_Senior,Seg_Female_Teen,Seg_Female_Young_Adult,Seg_Male_Adult,Seg_Male_Elder,Seg_Male_Middle_Aged,Seg_Male_Senior,Seg_Male_Teen,Seg_Male_Young_Adult,Seg_Other_Adult,Seg_Other_Middle_Aged,Seg_Other_Senior,Seg_Other_Teen,Seg_Other_Young_Adult
0,27,Female,54.28,1,True,8,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,0.060433,3.500000,0.437500,0.2743,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,42,Male,244.90,1,True,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,0.034208,0.272727,0.090909,-0.2257,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,43,Female,48.15,5,True,5,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,0.060433,1.142857,0.228571,-0.4757,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,32,Male,804.06,1,False,1,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,0.087799,1.250000,1.250000,0.0243,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
4,40,Female,755.61,5,True,7,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,0.236032,0.476190,0.068027,0.0243,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1623]:
df['Total_Amount'] = total_amount
df['Avg_Spending_Gender'] = df.groupby('Gender')['Total_Amount'].transform('mean')
df['Relative_Spending'] = df['Total_Amount'] / df['Avg_Spending_Gender']

In [1624]:
df['Age_Group'] = age_group
df['Avg_Spending_AgeGroup'] = df.groupby('Age_Group')['Total_Amount'].transform('mean')
df['AgeGroup_Spending_Deviation'] = df['Total_Amount'] - df['Avg_Spending_AgeGroup']

C:\Users\Andrei Necsulea\AppData\Local\Temp\ipykernel_22984\2163867979.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['Avg_Spending_AgeGroup'] = df.groupby('Age_Group')['Total_Amount'].transform('mean')

In [1625]:
df['Engagement_per_Year'] = df['Engagement_Score'] / df['Age']

In [1626]:
df['Payment_Method'] = payment_method
df['Gender_Payment'] = df['Gender'] + '_' + df['Payment_Method']
df = pd.get_dummies(df, columns=['Gender_Payment'])

In [1627]:
df['Gender'] = df['Gender'].map({'Male' : 1, 'Female' : 0, 'Other' : -1})

df['Age_x_Gender'] = df['Age'] * df['Gender']

In [1628]:
df.head()

,Age,Gender,Unit_Price,Quantity,Is_Returning_Customer,Delivery_Time_Days,Year,Month,Day,DayOfWeek,Quarter,IsWeekend,Discount_Percentage,Avg_Spending_City,Product_Beauty,Product_Books,Product_Electronics,Product_Fashion,Product_Food,Product_Home & Garden,Product_Sports,Product_Toys,Payment_Bank Transfer,Payment_Cash on Delivery,Payment_Credit Card,Payment_Debit Card,Payment_Digital Wallet,Device_Desktop,Device_Mobile,Device_Tablet,Engagement_Score,Pages_per_Minute,Browsing_to_Delivery_Ratio,Rating_Deviation,Age_Teen,Age_Young_Adult,Age_Adult,Age_Middle_Aged,Age_Senior,Age_Elder,Seg_Female_Adult,Seg_Female_Elder,Seg_Female_Middle_Aged,Seg_Female_Senior,Seg_Female_Teen,Seg_Female_Young_Adult,Seg_Male_Adult,Seg_Male_Elder,Seg_Male_Middle_Aged,Seg_Male_Senior,Seg_Male_Teen,Seg_Male_Young_Adult,Seg_Other_Adult,Seg_Other_Middle_Aged,Seg_Other_Senior,Seg_Other_Teen,Seg_Other_Young_Adult,Total_Amount,Avg_Spending_Gender,Relative_Spending,Age_Group,Avg_Spending_AgeGroup,AgeGroup_Spending_Deviation,Engagement_per_Year,Payment_Method,Gender_Payment_Female_Bank Transfer,Gender_Payment_Female_Cash on Delivery,Gender_Payment_Female_Credit Card,Gender_Payment_Female_Debit Card,Gender_Payment_Female_Digital Wallet,Gender_Payment_Male_Bank Transfer,Gender_Payment_Male_Cash on Delivery,Gender_Payment_Male_Credit Card,Gender_Payment_Male_Debit Card,Gender_Payment_Male_Digital Wallet,Gender_Payment_Other_Bank Transfer,Gender_Payment_Other_Cash on Delivery,Gender_Payment_Other_Credit Card,Gender_Payment_Other_Debit Card,Gender_Payment_Other_Digital Wallet,Age_x_Gender
0,27,0,54.28,1,True,8,2023,1,1,6,1,1,0.000000,925.557077,False,False,False,False,False,False,False,True,False,False,False,True,False,False,True,False,0.060433,3.500000,0.437500,0.2743,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,54.28,992.780602,0.054675,Adult,948.905918,-894.625918,0.002238,Debit Card,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,0
1,42,1,244.90,1,True,3,2023,1,1,6,1,1,0.000000,1088.249022,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,0.034208,0.272727,0.090909,-0.2257,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,244.90,977.835195,0.250451,Middle_Aged,993.312906,-748.412906,0.000814,Credit Card,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,42
2,43,0,48.15,5,True,5,2023,1,1,6,1,1,0.000000,894.606558,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,0.060433,1.142857,0.228571,-0.4757,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,240.75,992.780602,0.242501,Middle_Aged,993.312906,-752.562906,0.001405,Credit Card,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,0
3,32,1,804.06,1,False,1,2023,1,1,6,1,1,28.515285,1039.036262,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,0.087799,1.250000,1.250000,0.0243,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,574.78,977.835195,0.587809,Adult,948.905918,-374.125918,0.002744,Credit Card,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,32
4,40,0,755.61,5,True,7,2023,1,1,6,1,1,0.000000,1039.036262,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,0.236032,0.476190,0.068027,0.0243,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,3778.05,992.780602,3.805524,Middle_Aged,993.312906,2784.737094,0.005901,Cash on Delivery,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,0

In [1629]:
df.to_csv("feature_engineering.csv", index=False)